apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capston-frontend
  template:
    metadata:
      labels:
        app: capston-frontend
    spec:
      containers:
        - image: acrcapstondevcin.azurecr.io/capston-frontend-image:v1
          name: capston-containers
          ports:
            - containerPort: 80
            
          


